# This file was generated by GoReleaser. DO NOT EDIT.
cask "qase-tunnel" do
  version "0.1.0-beta.3"

  on_macos do
    on_intel do
      sha256 "afb41de5c81bae43e17abcc59fad7601008793c70b6e304d011436a6ea62d17f"
      url "https://github.com/qase-tms/qase-tunnel/releases/download/v#{version}/qase-tunnel_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3204eaad81229f03bb5967cd595c7cd94f207c6d55f1119914d7b9d5da0de0bf"
      url "https://github.com/qase-tms/qase-tunnel/releases/download/v#{version}/qase-tunnel_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8075e13ad7f7745bbbbab6a78c2f54846e8e8e89661524307a508b360f135eeb"
      url "https://github.com/qase-tms/qase-tunnel/releases/download/v#{version}/qase-tunnel_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0bb32935561b3fc178ca2885c5c6e605cb9b85066022acf2a21dc8c6708b5adb"
      url "https://github.com/qase-tms/qase-tunnel/releases/download/v#{version}/qase-tunnel_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qase-tunnel"
  desc "Customer-side CLI for Qase private-host tunnels"
  homepage "https://github.com/qase-tms/qase-tunnel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qase-tunnel"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qase-tunnel"]
    end
  end

  # No zap stanza required

end
