# This file was generated by GoReleaser. DO NOT EDIT.
cask "qase-tunnel" do
  version "0.1.0-beta.1"

  on_macos do
    on_intel do
      sha256 "d0394530867ef444cf97efe40a9ee3720c41f368335cbd5c0d7a849f3cbbe802"
      url "https://github.com/qase-tms/qase-tunnel/releases/download/v#{version}/qase-tunnel_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b7dd457dfdc357529c9a6d39f6c105d90b3ad7f75fa3a77c4313361a944f2be0"
      url "https://github.com/qase-tms/qase-tunnel/releases/download/v#{version}/qase-tunnel_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "137342baaa1cef9a383be0f188d6e42d7c212985a56a4feb5094dbb3e15decd3"
      url "https://github.com/qase-tms/qase-tunnel/releases/download/v#{version}/qase-tunnel_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6d5f8e8d4f563d30ae6db1905fafae698fdd99b2d1a66d99394db87eb6160e7"
      url "https://github.com/qase-tms/qase-tunnel/releases/download/v#{version}/qase-tunnel_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qase-tunnel"
  desc "Customer-side CLI for Qase private-host tunnels"
  homepage "https://github.com/qase-tms/qase-tunnel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qase-tunnel"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qase-tunnel"]
    end
  end

  # No zap stanza required

end
