# This file was generated by GoReleaser. DO NOT EDIT.
cask "qase-tunnel" do
  version "0.1.0-beta.2"

  on_macos do
    on_intel do
      sha256 "fa6e45481b58ff386c89a93d2d501d0a87f2fe6b6360885ae5aaa79d70904e69"
      url "https://github.com/qase-tms/qase-tunnel/releases/download/v#{version}/qase-tunnel_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b2f22ecb3c9b1a1698a1237af5ec32a909e6e1d3223c04859b2bdc4e34f29562"
      url "https://github.com/qase-tms/qase-tunnel/releases/download/v#{version}/qase-tunnel_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c33dc56c46bbefa18b1bf3a6f1a4c6845f63716b2c5851068dbbc0785e7767e"
      url "https://github.com/qase-tms/qase-tunnel/releases/download/v#{version}/qase-tunnel_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dbaf76363aad82dc0c5e64c818072dbeb60454bd5c5cf857df2cc92630982b35"
      url "https://github.com/qase-tms/qase-tunnel/releases/download/v#{version}/qase-tunnel_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qase-tunnel"
  desc "Customer-side CLI for Qase private-host tunnels"
  homepage "https://github.com/qase-tms/qase-tunnel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qase-tunnel"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qase-tunnel"]
    end
  end

  # No zap stanza required

end
