# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiden" do
  version "0.21.0"

  on_macos do
    on_arm do
      sha256 "c893ed638f0850d670194469e1740e540aa3a8094e727c728cf0b3d7c6a45913"
      url "https://github.com/qase-tms/homebrew-tap/releases/download/v#{version}/tiden_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "278148206018d66038abadd762740d01614ae2d6cc8d3284ab4015c49a51050e"
      url "https://github.com/qase-tms/homebrew-tap/releases/download/v#{version}/tiden_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "59fb4b0c23c83fd989db66c62fa88ddb2305663a696dfed0172a5e8d34a27c7e"
      url "https://github.com/qase-tms/homebrew-tap/releases/download/v#{version}/tiden_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cd652af537af88e9af2171ee39afe55898194577fd8544e482f5fb566fee53d3"
      url "https://github.com/qase-tms/homebrew-tap/releases/download/v#{version}/tiden_linux_amd64.tar.gz"
    end
  end

  name "tiden"
  desc "Tiden CLI — command-line interface for the Tiden platform"
  homepage "https://tiden.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiden"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiden"]
    end
  end

  # No zap stanza required
end
