# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiden" do
  version "0.24.0"

  on_macos do
    on_arm do
      sha256 "f31245f45996eed1f2607d849778b43be81628e6cae27f1f53709af44a4e110d"
      url "https://github.com/qase-tms/homebrew-tap/releases/download/v#{version}/tiden_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "59ba82b5dc048e9ef60bc9cb4fd6b4d813c2f9b29b8a57bb294e66d8973af99a"
      url "https://github.com/qase-tms/homebrew-tap/releases/download/v#{version}/tiden_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ce38a4b7b14e4b56ff0277b542355d924f0e4b884681c2a8125230ef39372d7f"
      url "https://github.com/qase-tms/homebrew-tap/releases/download/v#{version}/tiden_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b96a8910e0b337c4bef8e5975f0add6f7c5bd9b367c0e3c6edd44cd0f200dd64"
      url "https://github.com/qase-tms/homebrew-tap/releases/download/v#{version}/tiden_linux_amd64.tar.gz"
    end
  end

  name "tiden"
  desc "Tiden CLI — command-line interface for the Tiden platform"
  homepage "https://tiden.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiden"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiden"]
    end
  end

  # No zap stanza required
end
