# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiden" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "fb024393beced05065f4255824244c972d7311cdfaa73c3a6aca45c68eee4095"
      url "https://github.com/qase-tms/homebrew-tap/releases/download/v#{version}/tiden_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "26a997365a6b9496e231d636f8aafce9dba4f049cffd54fd94c99ee37151905a"
      url "https://github.com/qase-tms/homebrew-tap/releases/download/v#{version}/tiden_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a6d0a545ff41ebc8ee9c6fd4f278e0e3763e746994a0fea1f758b8d5848272d"
      url "https://github.com/qase-tms/homebrew-tap/releases/download/v#{version}/tiden_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa52a61fb89eaa85db46c3d815e290c7206eed2ec9183c697f92cec013d39704"
      url "https://github.com/qase-tms/homebrew-tap/releases/download/v#{version}/tiden_linux_arm64.tar.gz"
    end
  end

  name "tiden"
  desc "Tiden CLI — command-line interface for the Tiden platform"
  homepage "https://tiden.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiden"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tiden"]
    end
  end

  # No zap stanza required

end
